#pragma once

constexpr int    SCREEN_WIDTH = 800;
constexpr int    SCREEN_HEIGHT = 600;
constexpr double MOVE_SPEED = 5.0;
constexpr double MOUSE_SENSITIVITY = 0.003;
constexpr double SLICE_STEP = 0.03;
constexpr double SLICE_SMOOTH = 0.28;

enum BlockType : int
{
    BLOCK_AIR = 0,

    BLOCK_GRASS = 1,
    BLOCK_DIRT = 2,
    BLOCK_LOG = 3,
    BLOCK_LEAVES = 4,
    BLOCK_STONE = 5,
    BLOCK_PLANKS = 6,

    ITEM_STICK = 7,
    BLOCK_CRAFTING_TABLE = 8,

    BLOCK_DIAMOND_ORE = 9,
    BLOCK_GOLD_ORE = 10,
    BLOCK_IRON_ORE = 11,

    BLOCK_DIAMOND_BLOCK = 12,
    BLOCK_GOLD_BLOCK = 13,
    BLOCK_IRON_BLOCK = 14,

    ITEM_DIAMOND = 15,
    ITEM_GOLD_INGOT = 16,
    ITEM_IRON_INGOT = 17,
    ITEM_GOLD_NUGGET = 18,
    ITEM_IRON_NUGGET = 19,

    ITEM_APPLE = 20,
    ITEM_GOLDEN_APPLE = 21,

    ITEM_WOODEN_PICKAXE = 22,
    ITEM_WOODEN_AXE = 23,
    ITEM_WOODEN_SHOVEL = 24,
    ITEM_WOODEN_SWORD = 25,
    ITEM_WOODEN_HOE = 26,

    ITEM_STONE_PICKAXE = 27,
    ITEM_STONE_AXE = 28,
    ITEM_STONE_SHOVEL = 29,
    ITEM_STONE_SWORD = 30,
    ITEM_STONE_HOE = 31,

    ITEM_IRON_PICKAXE = 32,
    ITEM_IRON_AXE = 33,
    ITEM_IRON_SHOVEL = 34,
    ITEM_IRON_SWORD = 35,
    ITEM_IRON_HOE = 36,

    ITEM_IRON_HELMET = 37,
    ITEM_IRON_CHESTPLATE = 38,
    ITEM_IRON_LEGGINGS = 39,
    ITEM_IRON_BOOTS = 40,

    ITEM_GOLDEN_PICKAXE = 41,
    ITEM_GOLDEN_AXE = 42,
    ITEM_GOLDEN_SHOVEL = 43,
    ITEM_GOLDEN_SWORD = 44,
    ITEM_GOLDEN_HOE = 45,

    ITEM_GOLDEN_HELMET = 46,
    ITEM_GOLDEN_CHESTPLATE = 47,
    ITEM_GOLDEN_LEGGINGS = 48,
    ITEM_GOLDEN_BOOTS = 49,

    ITEM_DIAMOND_PICKAXE = 50,
    ITEM_DIAMOND_AXE = 51,
    ITEM_DIAMOND_SHOVEL = 52,
    ITEM_DIAMOND_SWORD = 53,
    ITEM_DIAMOND_HOE = 54,

    ITEM_DIAMOND_HELMET = 55,
    ITEM_DIAMOND_CHESTPLATE = 56,
    ITEM_DIAMOND_LEGGINGS = 57,
    ITEM_DIAMOND_BOOTS = 58,

    BLOCK_COBBLESTONE = 59,

    BLOCK_COAL_ORE = 60,
    ITEM_COAL = 61,
    BLOCK_COAL_BLOCK = 62,

    BLOCK_FURNACE = 63,

    MAX_BLOCK_TYPE = 64
};

inline constexpr double CYLINDER_R = 0.4;
inline constexpr double CYLINDER_H = 1.6;