#pragma once

constexpr int    SCREEN_WIDTH = 800;
constexpr int    SCREEN_HEIGHT = 600;
constexpr double MOVE_SPEED = 5.0;
constexpr double MOUSE_SENSITIVITY = 0.003;
constexpr double SLICE_STEP = 0.03;
constexpr double SLICE_SMOOTH = 0.28;

enum BlockType : int
{
    BLOCK_AIR = 0,

    BLOCK_GRASS = 1,
    BLOCK_DIRT = 2,
    BLOCK_LOG = 3,
    BLOCK_LEAVES = 4,
    BLOCK_STONE = 5,
    BLOCK_PLANKS = 6,

    BLOCK_STICK = 7,
    BLOCK_CRAFTING_TABLE = 8,

    BLOCK_DIAMOND_ORE = 9,
    BLOCK_GOLD_ORE = 10,
    BLOCK_IRON_ORE = 11,

    BLOCK_DIAMOND_BLOCK = 12,
    BLOCK_GOLD_BLOCK = 13,
    BLOCK_IRON_BLOCK = 14,

    BLOCK_DIAMOND = 15,
    BLOCK_GOLD_INGOT = 16,
    BLOCK_IRON_INGOT = 17,
    BLOCK_GOLD_NUGGET = 18,
    BLOCK_IRON_NUGGET = 19,

    BLOCK_APPLE = 20,
    BLOCK_GOLDEN_APPLE = 21,

    BLOCK_WOODEN_PICKAXE = 22,
    BLOCK_WOODEN_AXE = 23,
    BLOCK_WOODEN_SHOVEL = 24,
    BLOCK_WOODEN_SWORD = 25,
    BLOCK_WOODEN_HOE = 26,

    BLOCK_STONE_PICKAXE = 27,
    BLOCK_STONE_AXE = 28,
    BLOCK_STONE_SHOVEL = 29,
    BLOCK_STONE_SWORD = 30,
    BLOCK_STONE_HOE = 31,

    BLOCK_IRON_PICKAXE = 32,
    BLOCK_IRON_AXE = 33,
    BLOCK_IRON_SHOVEL = 34,
    BLOCK_IRON_SWORD = 35,
    BLOCK_IRON_HOE = 36,

    BLOCK_IRON_HELMET = 37,
    BLOCK_IRON_CHESTPLATE = 38,
    BLOCK_IRON_LEGGINGS = 39,
    BLOCK_IRON_BOOTS = 40,

    BLOCK_GOLDEN_PICKAXE = 41,
    BLOCK_GOLDEN_AXE = 42,
    BLOCK_GOLDEN_SHOVEL = 43,
    BLOCK_GOLDEN_SWORD = 44,
    BLOCK_GOLDEN_HOE = 45,

    BLOCK_GOLDEN_HELMET = 46,
    BLOCK_GOLDEN_CHESTPLATE = 47,
    BLOCK_GOLDEN_LEGGINGS = 48,
    BLOCK_GOLDEN_BOOTS = 49,

    BLOCK_DIAMOND_PICKAXE = 50,
    BLOCK_DIAMOND_AXE = 51,
    BLOCK_DIAMOND_SHOVEL = 52,
    BLOCK_DIAMOND_SWORD = 53,
    BLOCK_DIAMOND_HOE = 54,

    BLOCK_DIAMOND_HELMET = 55,
    BLOCK_DIAMOND_CHESTPLATE = 56,
    BLOCK_DIAMOND_LEGGINGS = 57,
    BLOCK_DIAMOND_BOOTS = 58,

    BLOCK_COBBLESTONE = 59,

    BLOCK_COAL_ORE = 60,
    BLOCK_COAL = 61,
    BLOCK_COAL_BLOCK = 62,

    BLOCK_FURNACE = 63,

    MAX_BLOCK_TYPE = 64
};

inline constexpr double CYLINDER_R = 0.4;
inline constexpr double CYLINDER_H = 1.6;